services:
  payroll-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      - APP_NAME=Payroll
    volumes:
      - ./database:/app/database

  hr-service:
    build: .
    ports:
      - "8082:8080"
    environment:
      - APP_NAME=HR
    volumes:
      - ./database:/app/database

networks:
  enterprise-network:
    driver: bridge
